### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by gangubai** [amaljoseph/face-recognition-attendance-system#1]
python facemaster.py
Qt: Cannot set locale modifiers: 
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[120, 115, 112, ..., 234, 234, 234],
       [118, 111, 107, ..., 234, 234, 234],
       [117, 109, 104, ..., 233, 233, 233],
       ...,
       [ 33,  28,  22, ...,  36,  36,  44],
       [ 32,  30,  26, ...,  41,  38,  43],
       [ 32,  32,  30, ...,  43,  36,  42]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[50, 50, 50, ..., 32, 32, 28],
       [49, 49, 50, ..., 28, 28, 32],
       [48, 49, 56, ..., 29, 29, 31],
       ...,
       [56, 54, 52, ..., 32, 33, 33],
       [54, 52, 51, ..., 32, 33, 33],
       [52, 51, 50, ..., 32, 33, 33]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[ 45,  44,  45, ..., 240, 240, 240],
       [ 44,  44,  46, ..., 240, 240, 240],
       [ 44,  45,  47, ..., 240, 240, 240],
       ...,
       [  0,  18, 105, ..., 234, 239, 245],
       [ 15,  65, 163, ..., 234, 239, 245],
       [  2,  41, 128, ..., 234, 239, 246]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[ 49,  49,  49, ..., 203, 183, 189],
       [ 48,  48,  48, ..., 204, 200, 205],
       [ 47,  47,  47, ..., 206, 210, 212],
       ...,
       [ 21,  21,  21, ..., 167, 163, 168],
       [ 21,  21,  22, ..., 166, 168, 169],
       [ 21,  21,  21, ..., 167, 163, 163]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[164, 171, 182, ...,  50,  50,  57],
       [179, 180, 184, ...,  45,  51,  68],
       [197, 191, 188, ...,  45,  64,  91],
       ...,
       [248, 248, 243, ..., 125, 123, 122],
       [239, 242, 238, ..., 124, 123, 122],
       [207, 215, 211, ..., 123, 122, 121]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[ 48,  28,  12, ..., 172, 173, 178],
       [ 32,  21,  14, ..., 170, 171, 176],
       [ 20,  17,  18, ..., 170, 175, 179],
       ...,
       [  7,   9,   9, ...,   6,   6,   6],
       [  8,   8,   9, ...,   6,   6,   6],
       [  8,   8,   8, ...,   6,   6,   6]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[128, 134, 138, ..., 134, 134, 144],
       [130, 136, 140, ..., 133, 132, 143],
       [131, 138, 142, ..., 132, 131, 141],
       ...,
       [118,  97,  70, ...,  68,  79,  74],
       [116,  93,  69, ...,  67,  78,  73],
       [112,  84,  67, ...,  68,  77,  74]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[241, 241, 241, ..., 236, 236, 236],
       [241, 241, 241, ..., 236, 236, 236],
       [241, 241, 241, ..., 236, 236, 236],
       ...,
       [164, 165, 165, ..., 225, 225, 225],
       [164, 165, 165, ..., 225, 225, 225],
       [164, 165, 165, ..., 225, 225, 225]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[158, 153, 163, ..., 116, 115, 118],
       [157, 152, 159, ..., 114, 115, 119],
       [159, 154, 160, ..., 111, 111, 113],
       ...,
       [230, 233, 230, ..., 172, 188, 203],
       [230, 233, 229, ..., 162, 180, 197],
       [231, 233, 229, ..., 154, 176, 194]], dtype=uint8), array([[199, 195, 188, ...,  75,  81,  81],
       [205, 204, 199, ...,  65,  67,  71],
       [212, 216, 216, ...,  65,  64,  68],
       ...,
       [ 48,  47,  46, ...,  35,  37,  40],
       [ 45,  44,  45, ...,  36,  38,  40],
       [ 44,  45,  48, ...,  38,  39,  40]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[array([[ 44,  51,  56, ...,  93,  96, 102],
       [ 44,  52,  59, ...,  93,  98, 104],
       [ 45,  55,  62, ...,  95, 100, 106],
       ...,
       [ 19,  22,  24, ..., 231, 231, 231],
       [ 20,  22,  24, ..., 232, 232, 232],
       [ 21,  23,  25, ..., 232, 232, 232]], dtype=uint8)]
------------------------------------------------------------
------------------------------------------------------------
Reading Image -\-
Detecting Face -\-
Face Detection Sucess - Confidence: 100% - Method: HaarCascade
[]
------------------------------------------------------------
Traceback (most recent call last):
  File "facemaster.py", line 19, in <module>
    faces, labels = prepare_training_data.prepare_training_data("training-data")
  File "/home/research_centre_gpu/Downloads/face-recognition-attendance-system-master/prepare_training_data.py", line 21, in prepare_training_data
    faces.append(face[0])
IndexError: list index out of range

Still we gave the  10 images in each  in s1 and s2 !
Please help to solve this error.
Thanks in advance!

**Comment by amaljoseph** [comment]
Have you modified my code?

**Comment by gangubai** [comment]
No!
